### ISSUE TITLE
Update addBoundary(function)

### ISSUE THREAD

**Issue by ArashMehraban** [ArashMehraban/Compressible-Hyperelasticity-Matlab#5]
@rezgarshakeri 

     The user should be able to provide an array of nodesets or sideset through sets variable. So here is what needs to be (ignore sidesets) done:
 Example:  imagine sets = ['ns_999', 'ns_998'] is given by user. 
 - [x] Test if the names in sets variable, i,e. 'ns_999', 'ns_998' in this example are valid nodesets in the DM. If any name is not valid, Error message
- [ ]  If they are valid, check if their corrsponding bdry_stat are ON, i.e, test if, in this example, ns_999_bdry_stat and  ns_998_bdry_stat are ON:
     If yes, do nothing and return DM,
     if No:
        I) turn the bdry_stat for each nodeset ON.
        II) call createLM()

**Comment by rezgarshakeri** [comment]
ok, I'll try

**Comment by rezgarshakeri** [comment]
I think I need a mesh file

**Comment by ArashMehraban** [comment]
uploaded a 12 elem mesh with nodesets and sidesets

**Comment by ArashMehraban** [comment]
I just aded another mesh with 6 nodesets. Also test your code with that. Choose 2 or 3 nodesets out of 6. Also, let the user choose 'all' instead of providing an array of all nodesets and test with that too.

**Comment by ArashMehraban** [comment]
One more comment:
The best data structure to pull all DM nodesets in and test if the user input are in there or not is a Map: https://www.mathworks.com/help/matlab/ref/containers.map.html

**Comment by ArashMehraban** [comment]
I have noticed you made a branch to test some ideas. I had make some significant changes. You need to work with the new DM and addBoundary() function.
